Make nrdb download strip typesetting characters
NoahTheDuke/netrunner-data pull request #46
Opened 2024-03-03 04:41 UTC by NBKelly

Basically I don't think it should ever be required to type unicode characters to play our game or use our deckbuilder.
Accents on characters are forgivable, but these fancy quotes are both extremely hard to distinguish and next to impossible to type.
Good luck remembering which of these two apostrophes you need to search for tomorrow's headline on netrunnerdb, and which one you need for aesop's pawnshop: `ʼ ’`
If they ever get goofier with these, it's easy enough to just add to the map.

2024-03-03 11:08 UTC, NoahTheDuke requested changes

2024-03-03 11:08 UTC, NoahTheDuke commented on src/nr_data/download.clj
> +  (letfn [(strip-typesetting-chars
Move to a top level defn plz.

2024-03-03 11:08 UTC, NoahTheDuke commented on src/nr_data/download.clj
> +            (if target-str
Given this is checking logical true, it should be (when target-str ...)

2024-03-03 11:08 UTC, NoahTheDuke commented on src/nr_data/download.clj
> +          raw-cards (map #(assoc % :title (strip-typesetting-chars (:title %))) raw-cards)
```suggestion
          raw-cards (mapv #(update % :title strip-typesetting-chars) raw-cards)
```

2024-03-17 19:05 UTC, NBKelly commented
OK, this should all be kosher now.

2024-03-17 19:07 UTC, merged